site_name: ER-Reason
site_url: https://alaalab.github.io/ER-Reason/
use_directory_urls: false

docs_dir: docs
site_dir: site

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: white
      accent: blue grey
  features:
    - content.code.annotations
    - content.code.copy

plugins: []

nav:
  - ER-Reason: index.md

extra_css:
  - stylesheets/extra.css
