site_name: ER-Reason
docs_dir: docs
site_dir: site

site_url: https://alaalab.github.io/ER-Reason/
use_directory_urls: false

theme:
  name: material
  palette:
    - scheme: default 
  features:
    - content.code.annotations
    - content.code.copy

plugins: []

nav:
  - ER-Reason: index.md

extra_css:
  - stylesheets/extra.css
